### ISSUE TITLE
Feature request: callback functions

### ISSUE THREAD

**Issue by laurensnl** [fabioquarantini/formchimp#3]
Great code, thank you for sharing!

Any change you would include callback functions? I would like to send an event to Google Analytics when the form has been successfully submitted. When an error occurs, another callback function could be run.

**Comment by inssitu** [comment]
Yes, it will be great

**Comment by fabioquarantini** [comment]
With the 1.2.0 version, I added two callbak and two events for error and success.

**Comment by laurensnl** [comment]
Thanks! Great addition!
