### ISSUE TITLE
Insecure code!

### ISSUE THREAD

**Issue by bitwombat** [fabioquarantini/formchimp#4]
Because this is a 100% JavaScript implementation, the browser has the MailChimp API key.  With this, anyone can go download, edit, or delete your lists, members, and any other assets associated with your MailChimp account.

Correct solutions have the JavaScript calling server-side PHP code, which holds or accesses the MailChimp API.  In this way, it is kept out of the user's hands.

**Comment by fabioquarantini** [comment]
This plugin doesn’t use Mailchimp API key, its using the same embedded form code Mailchimp provides for building a html form, but in Ajax and a cleaner code. ( http://kb.mailchimp.com/lists/signup-forms/add-a-signup-form-to-your-website )

**Comment by bitwombat** [comment]
Brilliant.  I stand corrected!
