### ISSUE TITLE
Multiple sign-up forms on one page

### ISSUE THREAD

**Issue by Dan9boi** [fabioquarantini/formchimp#5]
Hi, I have a page which have multiple signup forms. I've init'ed the forms induvidually, like this:

``` javascript
$('#jumbotron form').formchimp();
$('#sticky-sign-up form').formchimp();
```

But when i submit one of the forms, everything is fine, but when i go an submit the other form afterwards, the second form will respond in the first form's respnose div. How can this be?

I would like it to append the responses for one form, in itself (this) not the previously appended #mc-response div...

**Comment by fabioquarantini** [comment]
Hi,
you need set different "responseClass" in settings.

**Comment by Dan9boi** [comment]
like this:

``` javascript
$('#sticky-sign-up form').formchimp({
      responseClass: 'sticky-sign-up-response'
});
```

And the html:

``` html
<div class="sticky-sign-up-response"></div>
```

doesn't work :(

What am i doing wrong?

**Comment by fabioquarantini** [comment]
Try this:

``` javascript
$('#sticky-sign-up form-one').formchimp({
      responseClass: 'sticky-sign-up-response-one'
});

$('#sticky-sign-up form-two').formchimp({
      responseClass: 'sticky-sign-up-response-two'
});
```

And the html:

``` html
<div class="sticky-sign-up-response-one"></div>
<div class="sticky-sign-up-response-two"></div>
```
